name: Trigger API on file change

on:
  push:
    paths:
      - 'version.json' # adjust to the file(s) you want to monitor

jobs:
  notify-api:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}  # <-- this line was mis-indented
    steps:
      - name: Call external API
        run: |
          curl -X POST "$API_URL" \
          -H "Content-Type: application/json" \
          -d '{"content": "version.json was updated"}'
